Added game logic (Milestone 3)
mikethreels/tic_tac_toe pull request #3
Opened 2020-06-17 21:24 UTC by WinterCore

Changes:

- Create a `Player` class
- Refactor all the game logic into a separate class `Board`
- Add game-winning logic
- Add support for multiple board sizes
- Add the `Helper` Module that contains useful methods

2020-06-18 00:21 UTC, majovanilla requested changes
Hi team! :wave: 

## You did a *great* job on this project! 💜 

I have a few changes that you need to implement before moving forward. :point_down: 

- I suggest you add some instructions into the game interface on the console.
- I loved your enthusiasm for the project and how you added the option of changing the board size, but I see a lot of future troubles here and I suggest you go slow on the project and leave that for later. Check the comments to see the problems I encountered and then decide.
- Check the commented code below and implement the changes.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-06-18 00:21 UTC, majovanilla commented on bin/main.rb
> +) { |str| !str.empty? }
Nice job validating the user's name. You should add another one to avoid both users having the same name.

2020-06-18 00:21 UTC, majovanilla commented on bin/main.rb
> +  "#{name} please pick your shape no longer than 5 characters: ",
The word shape is kind of confusing. Maybe try to change it to symbol??

2020-06-18 00:21 UTC, majovanilla commented on bin/main.rb
> +size = Helper.read_integer(10)
This is SOO confusing!! I think you should stick to the traditional board. You are not providing instructions on the console on how to play it, so the rules are not clear.
I tried to play with a 5 rows board and even when I completed a whole row with the same symbol there was not a winner declared.
Also, if you have an odd number board, there is no way a player can win diagonally.

2020-06-18 00:21 UTC, majovanilla commented on bin/main.rb
> +require './lib/board.rb'
Remember to use require_relative when you are using a file not a gem.

2020-06-18 00:21 UTC, majovanilla commented on bin/main.rb
> +) { |str| !str.empty? && str.size < 6 && str != shape1 }
You are repeating the same code twice, once for each player. It would be better (remember DRY) to create two methods, one for the name and one for the "shape" or symbol and then calling them here.

2020-06-18 00:21 UTC, majovanilla commented on lib/board.rb
> +    end
Nice use of private methods

2020-06-18 00:21 UTC, majovanilla commented on lib/helper.rb
> +  def self.shape
You have a lot of methods in this module that are using `print`, `puts`, or `chomp` and that's against the [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/main_rb.png). Please fix that. TIP: you can return a string and then print it on main.rb if you must.

2020-06-18 00:21 UTC, majovanilla commented on lib/helper.rb
> +  end
This would be simpler if you don't let the user decide the size of the board.
Return a string instead of using print on the `lib` folder.

2020-06-18 00:21 UTC, majovanilla commented on lib/helper.rb
> +    end
You need to structure this method differently without using` gets.chomp` and `print`

2020-06-18 19:24 UTC, Dandush03 commented
# Status: 🔴 Required Changes 🔴 

## Great work applying previews changes, but you still miss one of my colleague reviews. I will point then right below:

- [ ] your lib/helper.rb is using get.chomp, remember that on this milestone the only place where you can use puts/print and get.chomb is at bin/main.rb
- [ ] user attr_accessor only where's needed. I can see that the player class has is using attr_accessor for the name, but it's only set up on the constructor.

### Beside that you've done a great job

# Happy Coding 💻

2020-06-19 01:49 UTC, davidmrtz-dev approved these changes
****
## Hi Team. 😄 
****
Great Job 💯 👍  @WinterCore @mikethreels , You correctly implemented the required changes.
You can move onto the next milestone. 🎊 
Happy coding! 😄 💻  
****
### Status: Approved. ✅
****

**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

2020-06-19 15:20 UTC, merged